version: "3.9"
networks:
  local-network:
services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    user: "104"
    networks:
      - local-network
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - local-network
  service:
    image: zio-rest
    container_name: service
    ports:
      - "8080:8080"
    networks:
      - local-network
