version: "3.9"
services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    user: "104"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
